apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-fastapi-server-app
  namespace: ml
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-server-app
  template:
    metadata:
      labels:
        app: fastapi-server-app
    spec:
      containers:
      - name: fastapi
        image: shsaronian/docker_challenges:fastapi-server
