apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-app-srv
  namespace: ml
spec:
  selector:
    app: fastapi-server-app
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      name: non-secure
      targetPort: web
      nodePort: 30445

